{{- if .Values.cloudflare.apiTokenSecretName }}
# Secret is expected to be created out-of-band (kubectl or sealed-secret). This template is here only for documentation purposes and disabled by default.
{{- end }}