{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  labels:
    {{- include "finance-app.labels" . | nindent 4 }}
spec:
  args:
    - name: service-name
    - name: prometheus-address
      value: http://kube-prometheus-stack-prometheus.monitoring:9090
  
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: "{{`{{args.prometheus-address}}`}}"
          query: |
            sum(rate(
              http_requests_total{
                service="{{`{{args.service-name}}`}}",
                status!~"5.."
              }[2m]
            )) 
            /
            sum(rate(
              http_requests_total{
                service="{{`{{args.service-name}}`}}"
              }[2m]
            ))
    
    - name: avg-response-time
      interval: 30s
      count: 5
      successCondition: result[0] <= 500
      failureLimit: 3
      provider:
        prometheus:
          address: "{{`{{args.prometheus-address}}`}}"
          query: |
            histogram_quantile(0.95,
              sum(rate(
                http_request_duration_seconds_bucket{
                  service="{{`{{args.service-name}}`}}"
                }[2m]
              )) by (le)
            ) * 1000
{{- end }}
