{{- if .Values.rollout.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-app.fullname" . }}-backend-stable
  labels:
    {{- include "finance-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    service-type: stable
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "finance-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-app.fullname" . }}-backend-canary
  labels:
    {{- include "finance-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    service-type: canary
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "finance-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
