apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server/app.yaml
  - kube-prometheus-stack/app.yaml
  - istio-base/app.yaml
  - argo-rollouts/app.yaml
  - istiod/app.yaml
  - istio-ingress/app.yaml
