args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS
serviceAccount:
  create: true
  annotations: {}
podLabels:
  Environment: lab
  shutdown: "true"
