apiVersion: v2
name: finfy-app-gateway
version: 0.1.0
description: Istio Gateway, VirtualServices and optional TLS Certificate for Finfy application
appVersion: "0.1.0"
type: application
keywords:
  - istio
  - gateway
  - virtualservice
  - certificate
sources:
  - https://github.com/danilouchoa/pobi
maintainers:
  - name: Finfy Team
    email: dev@finfy.me
