{{- if and .Values.ingress.enabled .Values.host }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.ingress.gatewayName }}
  labels:
    app.kubernetes.io/part-of: {{ include "finfy-app-gateway.fullname" . }}
  {{- if .Values.annotations }}
  annotations:
  {{- range $k, $v := .Values.annotations }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
{{ toYaml .Values.ingress.selector | indent 4 }}
  servers:
    - port:
        number: {{ .Values.ingress.httpPort }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.host | quote }}
    - port:
        number: {{ .Values.ingress.httpsPort }}
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.secretName }}
      hosts:
        - {{ .Values.host | quote }}
{{- end }}
