apiVersion: v2
name: finfy-backend
version: 0.1.0
description: Helm chart for Finfy backend service
appVersion: "0.1.0"
type: application
keywords:
  - backend
  - api
  - node
sources:
  - https://github.com/danilouchoa/pobi
maintainers:
  - name: Finfy Team
    email: dev@finfy.me
